---
title: "Client Report - Baby Names Analysis"
subtitle: "Course DS 250"
author: "Melanie Maldonado"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
#| label: libraries
#| include: false
import pandas as pd
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```


## Elevator pitch

This project looks at a dataset of baby names to see how name popularity changes over time. I wanted to understand which names are more common and how trends shift from year to year. I cleaned the data and grouped it to make it easier to analyze. Then I created a simple visualization to show how name counts change over time. This project helped me practice working with data and finding patterns in a real dataset

```{python}
#| label: project-data
#| code-summary: Read and format project data

# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
df = pd.read_csv("https://github.com/byuidatascience/data4names/raw/master/data-raw/names_year/names_year.csv")
```

__Highlight the Questions and Tasks__

## QUESTION|TASK 1

Analyze trends in baby name popularity over time

In this analysis, I explored how baby name popularity changes over time. After cleaning the data, I grouped the dataset by year to observe trends. This helped show how the number of names changes across different years. The visualization highlights patterns and makes it easier to see increases or decreases in name usage

```{python}
#| label: Q1
#| code-summary: Read and format data
# Include and execute your code here

```

_include figures in chunks and discuss your findings in the figure._

```{python}
#| label: Q1-chart
#| code-summary: plot example
#| fig-cap: "My useless chart"
#| fig-align: center
# Include and execute your code here
(
  ggplot(df.head(200), aes(x='name', y='AK')) + geom_bar(stat='identity')
)
```


```{python}
#| label: Q1-table
#| code-summary: table example
#| tbl-cap: "Not much of a table"
#| tbl-cap-location: top

# Include and execute your code here
mydat = (df.head(1000)
    .groupby('year')
    .sum()
    .reset_index()
    .tail(10)
    .filter(["year", "AK","AR"])
)
display(mydat)

```


## QUESTION|TASK 2

__COPY PASTE QUESTION|TASK 2 FROM THE PROJECT HERE__

_type your results and analysis here_

```{python}
#| label: Q2
#| code-summary: Read and format data
# Include and execute your code here


```

_include figures in chunks and discuss your findings in the figure._

```{python}
#| label: Q2-chart
#| code-summary: plot example
#| fig-cap: "My useless chart"
#| fig-align: center

# Include and execute your code here
# (
#   ggplot(df.head(200), aes(x='name', y='AK')) + geom_bar(stat='identity')
# )

```


```{python}
#| label: Q2-table
#| code-summary: table example
#| tbl-cap: "Not much of a table"
#| tbl-cap-location: top
# Include and execute your code here
# mydat = df.head(1000)\
#     .groupby('year')\
#     .sum()\
#     .reset_index()\
#     .tail(10)\
#     .filter(["year", "AK","AR"])

# display(mydat)

```


## QUESTION|TASK 3

__COPY PASTE QUESTION|TASK 3 FROM THE PROJECT HERE__

_type your results and analysis here_

```{python}
#| label: Q3
#| code-summary: Read and format data
# Include and execute your code here


```

_include figures in chunks and discuss your findings in the figure._

```{python}
#| label: Q3-chart
#| code-summary: plot example
#| fig-cap: "My useless chart"
#| fig-align: center
# Include and execute your code here
# Include and execute your code here
# (
#   ggplot(df.head(200), aes(x='name', y='AK')) + geom_bar(stat='identity')
# )
```


```{python}
#| label: Q3-table
#| code-summary: table example
#| tbl-cap: "Not much of a table"
#| tbl-cap-location: top
# Include and execute your code here
# mydat = df.head(1000)\
#     .groupby('year')\
#     .sum()\
#     .reset_index()\
#     .tail(10)\
#     .filter(["year", "AK","AR"])

# display(mydat)

```

## QUESTION|TASK 4

__COPY PASTE QUESTION|TASK 3 FROM THE PROJECT HERE__

_type your results and analysis here_

```{python}
#| label: Q4
#| code-summary: Read and format data
# Include and execute your code here


```

_include figures in chunks and discuss your findings in the figure._

```{python}
#| label: Q4-chart
#| code-summary: plot example
#| fig-cap: "My useless chart"
#| fig-align: center
# Include and execute your code here
# Include and execute your code here
# (
#   ggplot(df.head(200), aes(x='name', y='AK')) + geom_bar(stat='identity')
# )
```


```{python}
#| label: Q4-table
#| code-summary: table example
#| tbl-cap: "Not much of a table"
#| tbl-cap-location: top
# Include and execute your code here
# mydat = df.head(1000)\
#     .groupby('year')\
#     .sum()\
#     .reset_index()\
#     .tail(10)\
#     .filter(["year", "AK","AR"])

# display(mydat)

```

## QUESTION|TASK 5

__COPY PASTE QUESTION|TASK 3 FROM THE PROJECT HERE__

_type your results and analysis here_

```{python}
#| label: Q5
#| code-summary: Read and format data
# Include and execute your code here


```

_include figures in chunks and discuss your findings in the figure._

```{python}
#| label: Q5-chart
#| code-summary: plot example
#| fig-cap: "My useless chart"
#| fig-align: center
# Include and execute your code here
# Include and execute your code here
# (
#   ggplot(df.head(200), aes(x='name', y='AK')) + geom_bar(stat='identity')
# )
```


```{python}
#| label: Q5-table
#| code-summary: table example
#| tbl-cap: "Not much of a table"
#| tbl-cap-location: top
# Include and execute your code here
# mydat = df.head(1000)\
#     .groupby('year')\
#     .sum()\
#     .reset_index()\
#     .tail(10)\
#     .filter(["year", "AK","AR"])

# display(mydat)

```